### ISSUE TITLE
Getting the Orignal weight matrix.

### ISSUE THREAD

**Issue by vaibhav0195** [visym/keynet#2]
Hi, Thanks for this amazing repo.
This is an amazing paper too.

However, I want to retrain my model after its being key'd using the 'PermutationKeynet' function.
Is there a way by which I can get the pytorch-weights back, in the form of (N,C,H,W) ?

Any help is appreciated.
Regards and Thanks
Vaibhav

**Comment by jebyrne** [comment]
If you know the layer keys, and if the layer keys that you used are positive definite, then you can recover the original weights.  If you need to do this, I would recommend using the keying matrices based on Givens rotations, which have an inverse by construction.
