### ISSUE TITLE
'KeyedSensor' object has no attribute 'image'

### ISSUE THREAD

**Issue by nikosuenderhauf** [visym/keynet#3]
Thanks for publishing this very interesting work and the accompanying repository!

When running demo/lenet.ipynb I get the following error in the 6th cell:

```
--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-34-b8bd99fe936b> in <module>
      1 # This is the original image, resized to be (28x28), and input into the lenet network
----> 2 im_plain = sensor.decrypt().image().resize(512, 512, interp='nearest').show()

~/anaconda3/envs/privacy/lib/python3.7/site-packages/torch/nn/modules/module.py in __getattr__(self, name)
    574                 return modules[name]
    575         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 576             type(self).__name__, name))
    577 
    578     def __setattr__(self, name, value):

AttributeError: 'KeyedSensor' object has no attribute 'image'
```

I checked and `type(sensor.decrypt())` returns `<class 'keynet.system.KeyedSensor'>`
`vipy.version.VERSION` is `1.9.6`

`vars(sensor.decrypt()).keys()` is: `dict_keys(['_encryptkey', '_decryptkey', '_inshape', '_tensor', '_im', 'W', '_layertype'])`

Thank you for your help!

**Comment by nikosuenderhauf** [comment]
It seems `sensor.decrypt().image()` must be replaced by `sensor.decrypt().asimage()`?

**Comment by jebyrne** [comment]
Yes, that's right.  This has been resolved.
